version: "3"

services:
  jobmanager:
    image:  flink-case-image:latest
    command: jobmanager
    expose:
    - "6123"
    volumes:
    - "./data:/data"
    ports:
    - "8081:8081"
    environment:
    - CSV_FILE=/data/case.csv
    - OUTPUT_PATH=/data/
    - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
    - flink-case-network

  taskmanager:
    image:  flink-case-image:latest
    expose:
    - "6121"
    - "6122"
    volumes:
    - "./data:/data"
    depends_on:
    - jobmanager
    command: taskmanager
    environment:
    - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
    - flink-case-network

networks:
  flink-case-network:
    driver: bridge
